# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('body', wagtail.wagtailcore.fields.StreamField((('template', wagtail.wagtailcore.blocks.RawHTMLBlock()),))),
            ],
        ),
        migrations.DeleteModel(
            name='BaseEmail',
        ),
    ]
