# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagmail', '0002_auto_20170324_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('template', wagtail.wagtailcore.blocks.RawHTMLBlock()))),
        ),
    ]
