# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagmail', '0003_auto_20170324_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='id',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
