# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 09:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagmail', '0004_auto_20170324_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('template', wagtail.wagtailcore.blocks.RawHTMLBlock()),)),
        ),
    ]
