# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagmail', '0006_auto_20170824_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='name',
            new_name='subject',
        ),
    ]
